- meta/main.yml
- meta/runtime.yml
> Adding meta/runtime.yml file

- roles/jws/handlers/main.yml
- roles/jws/tasks/java_install.yml
- roles/jws/tasks/main.yml
> Notify Ansible to restart tomcat if (server|web|context).xml content changes

- roles/jws/defaults/main.yml
- roles/jws/templates/server.xml.j2
@gzaronikas a small, but most likely needed, feature :)
> Add support for bind_address overrides

- galaxy.yml
- playbook.yml
- roles/common_criteria/.yamllint
- roles/common_criteria/defaults/main.yml
- roles/common_criteria/defaults/main.yml.orig
- roles/common_criteria/defaults/main.yml.rej
- roles/common_criteria/meta/main.yml
- roles/common_criteria/tasks/checks_conf_files.yml
- roles/common_criteria/tasks/checks_root_dirs.yml
- roles/common_criteria/tasks/execute_xpath_and_assess_result.yml
- roles/common_criteria/tasks/execute_xpath_and_assess_result.yml.orig
- roles/common_criteria/tasks/fastpackage.yml
- roles/common_criteria/tasks/main.yml
- roles/common_criteria/tasks/process_context_xml.yml
- roles/common_criteria/tasks/remove_apps.yml
- roles/jws/defaults/main.yml
- roles/jws/templates/server.xml.j2
@gzaronikas As discussed, I've refactor the Common Criteria to use community.general.xml instead of the xpath CLI and added it again to the collection.
> Common criteria

- roles/jws/tasks/install.yml
- roles/jws/tasks/install/rhn.yml
Doing some testing I found out that the RHN Zipfles was broken, because the zipfiles were never unzipped...
> Fixup rhn_zipfiles install

- .github/workflows/ci.yml
- galaxy.yml
> Release v0.0.2

- .github/workflows/release.yml
- ansible.cfg
Commenting out release collection for now. Uploading through UI
> Commenting out release collection for now. Uploading through UI

- playbook.yml
Parameterize tomcat_home and update the URL to be more dynamic so that it will work with versions that are not equal to version 9.x.
> Parameterize tomcat home

- README.md
- molecule/default/molecule.yml
- molecule/rpm/converge.yml
- molecule/uninstall/molecule.yml
- roles/jws/defaults/main.yml
- roles/jws/tasks/main.yml
- roles/jws/tasks/sanity_checks/ajp.yml
- roles/jws/tasks/sanity_checks/https.yml
- roles/jws_validation/defaults/main.yml
Includes somes fixes and changes to add validation of connectors paramters.
> Missing documentation for enabling HTTPS connector

- README.md
Fixed [Issue 79](https://github.com/ansible-middleware/jws-ansible-playbook/issues/79)
> Add documentation on webapps deployment

- README.md
- playbook.yml
- roles/jws/tasks/install/rhn.yml
> docs: update for rhn_zipfiles method

- roles/jws/tasks/main.yml
> Removing broken interpolarization from task name

- README.md
- roles/jws/README.md
- roles/jws/vars/main.yml
> Populate JWS version/patch metadata, update docs

- .ansible-lint
- roles/jws/README.md
- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/main.yml
- roles/jws/vars/main.yml
> Rename variables to be consistent

- roles/jws/tasks/main.yml
- roles/jws/vars/main.yml
> Avoid failure when `jws_apply_patches` is true and no CP is available

- roles/jws/tasks/apply_cp.yml
- roles/jws/vars/main.yml
> `jws_apply_patches` also installs native CP when available

- README.md
- galaxy.yml
> Fix readme support

- README.md
- roles/jws/tasks/install/rhn.yml
- roles/jws/tasks/install/zipfiles.yml
> Fix JWS native archive installation

- README.md
Superseed[PR156](https://github.com/ansible-middleware/jws-ansible-playbook/pull/156)
> A stab at reorganizing the collections README to focus on JWS product

- README.md
When this PR is complete it will solve #98 :smile: Taking a stab at it so we can start workshopping the wording.
> First pass at adding tomcat-vault documentation

- roles/jws/README.md
> Organize configuration groups by specific features to make it easier to find

- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
> jws: only removes examples webapps by default.

- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/install/rpm.yml
- roles/jws/vars/main.yml
Issue: https://github.com/ansible-middleware/jws/issues/177
> jws: ensure that tc_vault pkg are install if install method is rpm

- roles/jws/tasks/apply_cp/main.yml
@guidograzioli That's a fix for jws-dot... The weird part is that I'm pretty I already added the missing folder that a few weeks ago... Weird.
> Add folder containing apply_cp.yml to fixed apply_cp* scenarios in jws-dot

- roles/jws/tasks/install/rpm.yml
- roles/jws/templates/server.xml.j2
Fixes #167 
Please do not merge, I'm still running some tests on those changes!
@guidograzioli and @csutherl  can you review ?
> jws: ensure default server.xml.j2 uses the recommanded https config

- README.md
- roles/jws/README.md
@csutherl as suggested again by Adam, we should bump the version of JWS to 5.7 in the README.
> README: Bump JWS version to latest, 5.7, in README.

- roles/jws/tasks/apply_cp/copy_cp_on_target_and_checksum.yml
- roles/jws/tasks/apply_cp/defaults.yml
- roles/jws/tasks/apply_cp/download_from_rhn.yml
- roles/jws/tasks/apply_cp/main.yml
- roles/jws/tasks/apply_cp/perform_update.yml
> JWS-2693 - Natives patch not applied

- roles/jws/tasks/apply_cp/download_from_rhn.yml
- roles/jws/tasks/install/download_from_rhn.yml
- roles/jws/tasks/rhn/download.yml
- roles/jws/tasks/rhn/search.yml
@guidograzioli we might want to move the content of the rhn folder to commons... 
Note I've tested the changes on Olympus and it works.
> Ensure download directory on controller is writeable

- molecule/preinstalledjdk/molecule.yml
- molecule/preinstalledjdk/vars.yml
- roles/jws/templates/systemd/tomcat.service.j2
- roles/jws_validation/tasks/service_status.yml
Also update the molecule test for preinstalled jdk to use version 17 (was: 18)
> Set correct exit code in systemd unit

- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/apply_cp/main.yml
- roles/jws/tasks/install/defaults.yml
[Fix] Added ternary filter in Jinja2 to conditionally set the archive_file_suffix variable. Fixing https://github.com/ansible-middleware/jws/issues/243
Signed-off: [vmouriki@redhat.com](mailto:vmouriki@redhat.com)
> Dynamic archive_file_suffix initialization

- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/install/rpm.yml
@guidograzioli Please review! Note that there is tagged run of jws-dot on Olympus to confirm this has no side effect downstream...
> Several enhacements on the rpm install

- roles/jws/defaults/main.yml
Issue: https://issues.redhat.com/browse/AMW-150
> AMW-150 [JWS] sudo is required when zips on controller

- roles/jws/tasks/main.yml
> Make system `tomcat` user account only be in `tomcat` group

- roles/jws/README.md
Issue: https://issues.redhat.com/browse/AMW-339
> AMW-339 JWS 5.8.0 release missing from README

- roles/jws/tasks/apply_cp/apply_cp.yml
- roles/jws/tasks/defaults.yml
> Determine if offline patch is available

- molecule/ajp_or_https/converge.yml
- molecule/default/converge.yml
- molecule/force_install/prepare.yml
- molecule/preinstalledjdk/converge.yml
- molecule/uninstall/converge.yml
- roles/jws/tasks/java_install.yml
Issue: https://issues.redhat.com/browse/AMW-426
> AMW-426 Make jws collection compliant with ansible-core 2.19

- README.md
Issue: https://github.com/ansible-middleware/jws/issues/296
> jws collection CI label is showing no status
