ansible-middleware/jws

- roles/jws/tasks/java_install.yml
@gzaronikas a small fix to make the java_install also works on Fedora
> Fix java_install to work on Fedora

- galaxy.yml
- meta/runtime.yml
this pr adjusts the tags (adds linux and infrastructure), these are specific to automation hub and help both our SEO as well users to list specific collections by use case (if these don't fit don't hesitate to change them, we just need 1 out of the list of 10 that is below at [0]) 
second change just updates the requires ansible version to `2.9.10`. This patch version was when everything in regards to collections was fully merged into ansible itself, so its better to have that listed. 
[0]
cloud
linux
networking
storage
security
windows
infrastructure
monitoring
tools
database
application
> update requires version and tags

- molecule/default/verify.yml
- roles/jws/README.md
- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/templates/server.xml.j2
- roles/jws/vars/main.yml
Fix [issue 48](https://github.com/ansible-middleware/jws-ansible-playbook/issues/48)
> Missing required variables to enable HTTPS

- roles/jws/README.md
This commit fixes the markdown table in the readme which wasn't formatted correctly :)
> Fix service configuration table markdown

- roles/jws/tasks/install/zipfiles.yml
Fixes [Issue 83](https://github.com/ansible-middleware/jws-ansible-playbook/issues/83)
> Misc: rm invalid vars from name during install

- roles/jws/README.md
- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/apply_cp.yml
- roles/jws/tasks/install/rhn.yml
- roles/jws/tasks/main.yml
- roles/jws/vars/main.yml
> Apply latest JWS cumulative patch when `jws_apply_patches` is True

- .ansible-lint
- playbook.yml
- roles/jws/README.md
- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/uninstall.yml
- roles/jws/vars/main.yml
Update playbook to be simpler and rely on defaults rather than requiring settings
Remove download pre-task since zipfiles method does that for you
Switch tomcat_home default from jws to apache tomcat file location (in line with other defaults)
Update tomcat_zipfile_url defaults to use the split which is more dynamic
> Update playbook to utilize variable defaults

- README.md
- roles/jws/README.md
- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/install/fetch_zipfile_from_rhn_and_deploy.yml
- roles/jws/tasks/install/rhn.yml
- roles/jws/tasks/install/zipfiles.yml
Fixed #73 (and reduce code duplication)
> The JWS installation option should allow you to exclude natives

- roles/jws/tasks/main.yml
This change prevents setting ownership and modes to `tomcat_install_dir` when it exists (ie. when the it is defined as /opt).
Another task after the directory creation ensures correct ownership for tomcat.home already
> fix: tomcat.user owning existing directories

- roles/jws/tasks/apply_cp.yml
I was testing out `jws_apply_patches` and noticed that it wasn't working. The patch file check was always skipped and erroneously logging that it had already been applied when it actually had not been. I tweaked it a bit and it works for me now. I also moved the marker file to sit next to `version.txt` rather than in `/opt` (by default) so that we don't leave files outside of `$JWS_HOME`.
> Adjustments to the apply_cp.yml logic

- roles/jws/tasks/systemd/selinux.yml
> selinux policy allows tomcat to listen to non-default ports

- roles/jws/tasks/apply_cp.yml
- roles/jws/tasks/install.yml
- roles/jws/tasks/install/rhn.yml
- roles/jws/tasks/install/rpm.yml
- roles/jws/tasks/install/zipfiles.yml
- roles/jws/tasks/main.yml
> Name all tasks

- roles/jws/README.md
- roles/jws/defaults/main.yml
The connectorPort for modcluster should be one of the connectors from Tomcat rather than the management port for modcluster, by default we set the HTTP connector since it's the only default connector available
> Update modcluster connector port default

- roles/jws/tasks/install/rpm.yml
Because of string mismatch it always shows "Perform remove jws5"
> Fix string mismatch with groupinstall

- roles/jws/tasks/main.yml
@sabre1041 @guidograzioli I've added an override variable, because I'm pretty sure this 0600 came from the Common Criteria recommendation. So, some users, may need to change it.
> jws: set 0640 instead of 0600 for configuration files

- roles/jws/tasks/install/deploy_archive.yml
Fix issue #188 
@guidograzioli turns out, we only use stat: on the controller once. The two other occurences are going to be refactored when #189 is finished.
> enhancement: replace stat: with jinja2 exists on controller

- molecule/ajp_or_https/converge.yml
- molecule/ajp_or_https/molecule.yml
- molecule/ajp_or_https/verify.yml
- molecule/default/converge.yml
- molecule/default/verify.yml
- molecule/force_install/converge.yml
- molecule/force_install/verify.yml
- molecule/override_server_xml/converge.yml
- molecule/override_server_xml/molecule.yml
- molecule/override_server_xml/verify.yml
- molecule/uninstall/converge.yml
- molecule/uninstall/molecule.yml
- playbooks/playbook.yml
- roles/jws/tasks/install/zipfiles.yml
- roles/jws/tasks/main.yml
- roles/jws/templates/systemd/service.sh.j2
- roles/jws_validation/defaults/main.yml
- roles/jws_validation/meta/argument_specs.yml
- roles/jws_validation/tasks/jws_version.yml
- roles/jws_validation/tasks/main.yml
* Fix issue reading PID from very long service cmdlines
* Reduce redundant defaults in molecule, downstream testing
* Make jws_home really configurable
> Jws validation ds defaults

- README.md
@csutherl As Adam smartly pointed out, we should remove the Beta qualifiers from the README. WDYT? Can we double check the content of this PR, see if it what it should be?
> README: Remove 'beta' for release and add link to downstream release

- roles/jws/tasks/systemd/selinux.yml
Although labeling the HTTP ports causes no issue, we don't want to halfway enable selinux so moving it inside the block with the rest of the selinux tasks
> Reorganize selinux http port labeling task

- galaxy.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/systemd/selinux.yml
#209 
note this won't work in a ubi container since selinux-policy-devel has been removed
> Revert selinux policy postinstall filenames

- roles/jws/tasks/java_install.yml
- roles/jws/tasks/systemd/systemd.yml
This is easier and more reliable, since it supports having the JDK rpm being updated outside the collection.
> Use alternatives, not rpm, to determine java_home

- roles/jws/tasks/apply_cp/apply_cp.yml
- roles/jws/tasks/apply_cp/download_from_rhn.yml
- roles/jws/tasks/apply_cp/perform_update.yml
- roles/jws/tasks/apply_cp/prereqs.yml
Fix for offline patch installation with zips. 
Tested with the following playbooks:
Apply patch:
- name: "Red Hat JBoss Web Server installation and configuration"
hosts: all
become: True
vars:
zipfile_name: "jws-5.7.0-application-server.zip"
jws_apply_patches: True
patch_bundle: "jws-5.7.4-application-server.zip"
jws_version: 5.7.0
roles:
- jws
Do not apply patch:
- name: "Red Hat JBoss Web Server installation and configuration"
hosts: all
become: True
vars:
zipfile_name: "jws-5.7.0-application-server.zip"
jws_apply_patches: False
patch_bundle: "jws-5.7.4-application-server.zip"
jws_version: 5.7.0
roles:
- jws
> Fix offline patch installation

- meta/runtime.yml
Fixes linting warning: "requires_ansible key must be set to a supported version".
> Change requires_ansible key to a supported version

- README.md
Issue: https://issues.redhat.com/browse/AMWSUP-17
> AMWSUP-17 JWS Ansible Hub documentation link broken

- roles/jws/README.md
- roles/jws/tasks/java_install.yml
- roles/jws/tasks/main.yml
- roles/jws_validation/tasks/catalina_out.yml
Issue: https://issues.redhat.com/browse/AMW-133
There are two variables utilized to configure the Java Development Kit (JDK) for the jws collection. The first variable, "jws_java_version," facilitates the installation of an OpenJDK with the specified version. The alternative is to employ "jws_java_home," allowing users to specify the path to their Java installation.
Before this fix, There were two scenarios - when both variables were applied or neither were applied led to complications, resulting in a malfunctioning JWS installation. Now with this fix, we have refined the collection process. Now, if "jws_java_home" is set, "jws_java_version" will be disregarded. Additionally, if a user attempts to set both variables at the same time, then an ERROR will be triggered, prompting the …
> AMW-133 [JWS] Allow automatic recognition of Java

- roles/jws/tasks/defaults.yml
- roles/jws/tasks/install/force_install.yml
Use bare variables in defaults.yml to workaround ansible changes in https://access.redhat.com/security/cve/CVE-2023-5764  (core >= 2.14.12)
> Workaround AMW-185

- README.md
- meta/runtime.yml
- roles/jws/defaults/main.yml
- roles/jws/meta/main.yml
- roles/jws/tasks/apply_cp/copy_cp_on_target_and_checksum.yml
- roles/jws/tasks/apply_cp/download_from_rhn.yml
- roles/jws/tasks/defaults.yml
- roles/jws/tasks/install/deploy_archive.yml
- roles/jws/tasks/main.yml
- ansible-core==2.13 is EOL, updating minimum version to 2.14.0
- AMW-186 do not contact JbossNetwork (ie. no credentials needed) when nto applying patches and zipfile is locally available
- linter
> AMW-186, linter, and ansible-core >=2.14

- molecule/ajp_or_https/prepare.yml
- molecule/common_prepare.yml
- molecule/override_server_xml/verify.yml
- molecule/preinstalledjdk/molecule.yml
- molecule/preinstalledjdk/prepare.yml
- roles/jws/handlers/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/install/force_install.yml
- roles/jws/tasks/install/url.yml
- roles/jws/tasks/install/zipfiles.yml
- roles/jws/tasks/main.yml
- roles/jws/tasks/systemd/disable.yml
- roles/jws/tasks/systemd/service.yml
- roles/jws/tasks/systemd/stop.yml
- roles/jws/tasks/systemd/systemd.yml
- roles/jws/tasks/uninstall.yml
- roles/jws_validation/tasks/catalina_out.yml
Note that previously become: true was needed in the playbook itself, but with these changes, it's no longer required.
> AMW-196 Usage of become inside the jws role

- roles/jws/meta/argument_specs.yml
- roles/jws/tasks/defaults.yml
When `jws_selinux_enabled` is set to True, `jws_native` also needs to be set to True; this changeset adds a check that verifies said condition, and updates jws_native default to True
> Update default for `jws_native`

- roles/jws/README.md
- roles/jws/defaults/main.yml
- roles/jws/meta/argument_specs.yml
- roles/jws/vars/main.yml
The role parameter `jws_conf_loggging` contains a spelling error. This change renames the parameter to `jws_conf_logging`.
> fix typo in variable name

- roles/jws/defaults/main.yml
- roles/jws/tasks/fastpackage.yml
- roles/jws/tasks/rhn/search.yml
- roles/jws/vars/main.yml
There are still warnings for the validation role, which is probably not so important.
> Fix linter warnings for the jws role
